"""edit products.py

Revision ID: 2b02ab7a844c
Revises: f904aabe6fc2
Create Date: 2025-12-16 16:38:28.202924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b02ab7a844c'
down_revision: Union[str, Sequence[str], None] = 'f904aabe6fc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('last_supply', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'last_supply')
    # ### end Alembic commands ###
