"""add type enum to supplies

Revision ID: faf8508e8b3f
Revises: 3014bfd83d5b
Create Date: 2025-12-18 07:19:16.383848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'faf8508e8b3f'
down_revision: Union[str, Sequence[str], None] = '3014bfd83d5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    type_enum = postgresql.ENUM('SUPPLY', 'WRITE_OFF', 'TAKEN', name='type_enum')
    type_enum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplies', sa.Column('action_type', postgresql.ENUM('SUPPLY', 'WRITE_OFF', 'TAKEN', name='type_enum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplies', 'action_type')
    # ### end Alembic commands ###
    type_enum = postgresql.ENUM('SUPPLY', 'WRITE_OFF', 'TAKEN', name='type_enum')
    type_enum.drop(op.get_bind())
